import 'package:ari/data/models/album.dart';
import 'package:ari/data/models/track.dart';
import 'package:ari/domain/entities/playlist_trackitem.dart';
import 'package:ari/domain/entities/playlist.dart';

class MockData {
  static List<Album> getLatestAlbums() {
    return [
      Album(
        id: 1,
        title: 'Pain',
        artist: 'Chris Jones',
        genre: 'jazz',
        coverUrl: 'https://example.com/album_cover_1.jpg',
        releaseDate: DateTime(2025, 1, 10),
      ),
      Album(
        id: 2,
        title: 'Winter Love',
        artist: 'Alice Kim',
        genre: 'jazz',
        coverUrl: 'https://example.com/album_cover_2.jpg',
        releaseDate: DateTime(2025, 2, 14),
      ),
      Album(
        id: 3,
        title: 'Autumn Breeze',
        artist: 'Bob Lee',
        genre: 'hiphop',
        coverUrl: 'https://example.com/album_cover_3.jpg',
        releaseDate: DateTime(2025, 3, 20),
      ),
      Album(
        id: 4,
        title: 'Spring Bloom',
        artist: 'Jane Park',
        genre: 'hiphop',

        coverUrl: 'https://example.com/album_cover_4.jpg',
        releaseDate: DateTime(2025, 4, 5),
      ),
      Album(
        id: 5,
        title: 'Night Sky',
        artist: 'Mason Lee',
        genre: 'jazz',

        coverUrl: 'https://example.com/album_cover_5.jpg',
        releaseDate: DateTime(2025, 5, 30),
      ),
      Album(
        id: 6,
        title: 'Sunny Days',
        artist: 'Ellen Kim',
        genre: 'jazz',

        coverUrl: 'https://example.com/album_cover_6.jpg',
        releaseDate: DateTime(2025, 6, 15),
      ),
      Album(
        id: 7,
        title: 'Rainy Mood',
        artist: 'Mark Choi',
        genre: 'hiphop',

        coverUrl: 'https://example.com/album_cover_7.jpg',
        releaseDate: DateTime(2025, 7, 22),
      ),
      Album(
        id: 8,
        title: 'Ocean Waves',
        artist: 'Lily Chen',
        genre: 'jazz',

        coverUrl: 'https://example.com/album_cover_8.jpg',
        releaseDate: DateTime(2025, 8, 3),
      ),
      Album(
        id: 9,
        title: 'Mountain High',
        artist: 'Sam Woo',
        genre: 'jazz',
        coverUrl: 'https://example.com/album_cover_9.jpg',
        releaseDate: DateTime(2025, 9, 18),
      ),
      Album(
        id: 10,
        title: 'City Lights',
        artist: 'Nina Park',
        genre: 'band',
        coverUrl: 'https://example.com/album_cover_10.jpg',
        releaseDate: DateTime(2025, 10, 25),
      ),
    ];
  }

  static List<Album> getPopularAlbums() {
    return [
      Album(
        id: 11,
        title: 'Summer Vibes',
        artist: 'DJ Max',
        genre: 'hiphop',

        coverUrl: 'https://example.com/album_cover_11.jpg',
        releaseDate: DateTime(2024, 6, 1),
      ),
      Album(
        id: 12,
        title: 'Golden Hits',
        artist: 'Various Artists',
        genre: 'jazz',
        coverUrl: 'https://example.com/album_cover_12.jpg',
        releaseDate: DateTime(2023, 12, 1),
      ),
      Album(
        id: 13,
        title: 'Rhythm Nation',
        artist: 'Beat Crew',
        genre: 'hiphop',

        coverUrl: 'https://example.com/album_cover_13.jpg',
        releaseDate: DateTime(2024, 1, 15),
      ),
      Album(
        id: 14,
        title: 'Electric Pulse',
        artist: 'Neon Lights',
        genre: 'band',

        coverUrl: 'https://example.com/album_cover_14.jpg',
        releaseDate: DateTime(2024, 2, 28),
      ),
      Album(
        id: 15,
        title: 'Vintage Vibes',
        artist: 'Retro Beats',
        genre: 'jazz',

        coverUrl: 'https://example.com/album_cover_15.jpg',
        releaseDate: DateTime(2024, 3, 10),
      ),
      Album(
        id: 16,
        title: 'Rock Anthem',
        artist: 'The Strikers',
        genre: 'acoustic',

        coverUrl: 'https://example.com/album_cover_16.jpg',
        releaseDate: DateTime(2024, 4, 20),
      ),
      Album(
        id: 17,
        title: 'Indie Dreams',
        artist: 'Dreamers',
        genre: 'rnb',

        coverUrl: 'https://example.com/album_cover_17.jpg',
        releaseDate: DateTime(2024, 5, 5),
      ),
      Album(
        id: 18,
        title: 'Pop Explosion',
        artist: 'Starburst',
        genre: 'hiphop',

        coverUrl: 'https://example.com/album_cover_18.jpg',
        releaseDate: DateTime(2024, 6, 18),
      ),
      Album(
        id: 19,
        title: 'Folk Tales',
        artist: 'The Wanderers',
        genre: 'rnb',

        coverUrl: 'https://example.com/album_cover_19.jpg',
        releaseDate: DateTime(2024, 7, 30),
      ),
      Album(
        id: 20,
        title: 'Smooth Jazz',
        artist: 'Jazz Masters',
        genre: 'jazz',

        coverUrl: 'https://example.com/album_cover_20.jpg',
        releaseDate: DateTime(2024, 8, 12),
      ),
    ];
  }

  // static List<Playlist> getPopularPlaylists() {
  //   return [
  //     Playlist(
  //       id: 1,
  //       title: 'Top 50 K-Pop',
  //       isPublic: true,
  //       shareCount: 100, // 예시 값
  //       tracks: [
  //         PlaylistTrackItem(
  //           track: Track(
  //             trackId: 1,
  //             trackTitle: 'song1',
  //             artistName: 'Artist1',
  //             composer: [''],
  //             lyricist: [''],
  //             albumId: 1,
  //             trackFileUrl: '',
  //             lyric: '',
  //             trackNumber: 1,
  //             commentCount: 0,
  //             createdAt: DateTime.now().toString(),
  //             coverUrl: null,
  //             trackLikeCount: 0,
  //             comments: [],
  //           ),
  //           trackOrder: 1,
  //         ),
  //         PlaylistTrackItem(
  //           track: Track(
  //             trackId: 2,
  //             trackTitle: 'song2',
  //             artistName: 'Artist2',
  //             composer: [''],
  //             lyricist: [''],
  //             albumId: 1,
  //             trackFileUrl: '',
  //             lyric: '',
  //             trackNumber: 2,
  //             commentCount: 0,
  //             createdAt: DateTime.now().toString(),
  //             coverUrl: null,
  //             trackLikeCount: 0,
  //             comments: [],
  //           ),
  //           trackOrder: 2,
  //         ),
  //         PlaylistTrackItem(
  //           track: Track(
  //             trackId: 3,
  //             trackTitle: 'song3',
  //             artistName: 'Artist3',
  //             composer: [''],
  //             lyricist: [''],
  //             albumId: 1,
  //             trackFileUrl: '',
  //             lyric: '',
  //             trackNumber: 3,
  //             commentCount: 0,
  //             createdAt: DateTime.now().toString(),
  //             coverUrl: null,
  //             trackLikeCount: 0,
  //             comments: [],
  //           ),
  //           trackOrder: 3,
  //         ),
  //       ],
  //     ),
  //     Playlist(
  //       id: 2,
  //       title: 'Relaxing Jazz',
  //       isPublic: true,
  //       shareCount: 50, // 예시 값
  //       tracks: [
  //         PlaylistTrackItem(
  //           track: Track(
  //             trackId: 4,
  //             trackTitle: 'song1',
  //             artistName: 'Artist1',
  //             composer: [''],
  //             lyricist: [''],
  //             albumId: 2,
  //             trackFileUrl: '',
  //             lyric: '',
  //             trackNumber: 1,
  //             commentCount: 0,
  //             createdAt: DateTime.now().toString(),
  //             coverUrl: null,
  //             trackLikeCount: 0,
  //             comments: [],
  //           ),
  //           trackOrder: 1,
  //         ),
  //         PlaylistTrackItem(
  //           track: Track(
  //             trackId: 5,
  //             trackTitle: 'song2',
  //             artistName: 'Artist2',
  //             composer: [''],
  //             lyricist: [''],
  //             albumId: 2,
  //             trackFileUrl: '',
  //             lyric: '',
  //             trackNumber: 2,
  //             commentCount: 0,
  //             createdAt: DateTime.now().toString(),
  //             coverUrl: null,
  //             trackLikeCount: 0,
  //             comments: [],
  //           ),
  //           trackOrder: 2,
  //         ),
  //       ],
  //     ),
  //     Playlist(
  //       id: 3,
  //       title: 'Rock Classics',
  //       isPublic: true,
  //       shareCount: 75, // 예시 값
  //       tracks: [
  //         PlaylistTrackItem(
  //           track: Track(
  //             trackId: 6,
  //             trackTitle: 'song1',
  //             artistName: 'Artist1',
  //             composer: [''],
  //             lyricist: [''],
  //             albumId: 3,
  //             trackFileUrl: '',
  //             lyric: '',
  //             trackNumber: 1,
  //             commentCount: 0,
  //             createdAt: DateTime.now().toString(),
  //             coverUrl: null,
  //             trackLikeCount: 0,
  //             comments: [],
  //           ),
  //           trackOrder: 1,
  //         ),
  //         PlaylistTrackItem(
  //           track: Track(
  //             trackId: 7,
  //             trackTitle: 'song2',
  //             artistName: 'Artist2',
  //             composer: [''],
  //             lyricist: [''],
  //             albumId: 3,
  //             trackFileUrl: '',
  //             lyric: '',
  //             trackNumber: 2,
  //             commentCount: 0,
  //             createdAt: DateTime.now().toString(),
  //             coverUrl: null,
  //             trackLikeCount: 0,
  //             comments: [],
  //           ),
  //           trackOrder: 2,
  //         ),
  //       ],
  //     ),
  //     Playlist(
  //       id: 4,
  //       title: 'Hip Hop Beats',
  //       isPublic: true,
  //       shareCount: 80, // 예시 값
  //       tracks: [
  //         PlaylistTrackItem(
  //           track: Track(
  //             trackId: 8,
  //             trackTitle: 'song1',
  //             artistName: 'Artist1',
  //             composer: [''],
  //             lyricist: [''],
  //             albumId: 4,
  //             trackFileUrl: '',
  //             lyric: '',
  //             trackNumber: 1,
  //             commentCount: 0,
  //             createdAt: DateTime.now().toString(),
  //             coverUrl: null,
  //             trackLikeCount: 0,
  //             comments: [],
  //           ),
  //           trackOrder: 1,
  //         ),
  //         PlaylistTrackItem(
  //           track: Track(
  //             trackId: 9,
  //             trackTitle: 'song2',
  //             artistName: 'Artist2',
  //             composer: [''],
  //             lyricist: [''],
  //             albumId: 4,
  //             trackFileUrl: '',
  //             lyric: '',
  //             trackNumber: 2,
  //             commentCount: 0,
  //             createdAt: DateTime.now().toString(),
  //             coverUrl: null,
  //             trackLikeCount: 0,
  //             comments: [],
  //           ),
  //           trackOrder: 2,
  //         ),
  //       ],
  //     ),
  //     Playlist(
  //       id: 5,
  //       title: 'Indie Mix',
  //       isPublic: true,
  //       shareCount: 40, // 예시 값
  //       tracks: [
  //         PlaylistTrackItem(
  //           track: Track(
  //             trackId: 10,
  //             trackTitle: 'song1',
  //             artistName: 'Artist1',
  //             composer: [''],
  //             lyricist: [''],
  //             albumId: 5,
  //             trackFileUrl: '',
  //             lyric: '',
  //             trackNumber: 1,
  //             commentCount: 0,
  //             createdAt: DateTime.now().toString(),
  //             coverUrl: null,
  //             trackLikeCount: 0,
  //             comments: [],
  //           ),
  //           trackOrder: 1,
  //         ),
  //         PlaylistTrackItem(
  //           track: Track(
  //             trackId: 11,
  //             trackTitle: 'song2',
  //             artistName: 'Artist2',
  //             composer: [''],
  //             lyricist: [''],
  //             albumId: 5,
  //             trackFileUrl: '',
  //             lyric: '',
  //             trackNumber: 2,
  //             commentCount: 0,
  //             createdAt: DateTime.now().toString(),
  //             coverUrl: null,
  //             trackLikeCount: 0,
  //             comments: [],
  //           ),
  //           trackOrder: 2,
  //         ),
  //       ],
  //     ),
  //     Playlist(
  //       id: 6,
  //       title: 'Workout Mix',
  //       isPublic: true,
  //       shareCount: 90, // 예시 값
  //       tracks: [
  //         PlaylistTrackItem(
  //           track: Track(
  //             trackId: 12,
  //             trackTitle: 'song1',
  //             artistName: 'Artist1',
  //             composer: [''],
  //             lyricist: [''],
  //             albumId: 6,
  //             trackFileUrl: '',
  //             lyric: '',
  //             trackNumber: 1,
  //             commentCount: 0,
  //             createdAt: DateTime.now().toString(),
  //             coverUrl: null,
  //             trackLikeCount: 0,
  //             comments: [],
  //           ),
  //           trackOrder: 1,
  //         ),
  //         PlaylistTrackItem(
  //           track: Track(
  //             trackId: 13,
  //             trackTitle: 'song2',
  //             artistName: 'Artist2',
  //             composer: [''],
  //             lyricist: [''],
  //             albumId: 6,
  //             trackFileUrl: '',
  //             lyric: '',
  //             trackNumber: 2,
  //             commentCount: 0,
  //             createdAt: DateTime.now().toString(),
  //             coverUrl: null,
  //             trackLikeCount: 0,
  //             comments: [],
  //           ),
  //           trackOrder: 2,
  //         ),
  //       ],
  //     ),
  //     Playlist(
  //       id: 7,
  //       title: 'Chill Vibes',
  //       isPublic: true,
  //       shareCount: 70, // 예시 값
  //       tracks: [
  //         PlaylistTrackItem(
  //           track: Track(
  //             trackId: 14,
  //             trackTitle: 'song1',
  //             artistName: 'Artist1',
  //             composer: [''],
  //             lyricist: [''],
  //             albumId: 7,
  //             trackFileUrl: '',
  //             lyric: '',
  //             trackNumber: 1,
  //             commentCount: 0,
  //             createdAt: DateTime.now().toString(),
  //             coverUrl: null,
  //             trackLikeCount: 0,
  //             comments: [],
  //           ),
  //           trackOrder: 1,
  //         ),
  //         PlaylistTrackItem(
  //           track: Track(
  //             trackId: 15,
  //             trackTitle: 'song2',
  //             artistName: 'Artist2',
  //             composer: [''],
  //             lyricist: [''],
  //             albumId: 7,
  //             trackFileUrl: '',
  //             lyric: '',
  //             trackNumber: 2,
  //             commentCount: 0,
  //             createdAt: DateTime.now().toString(),
  //             coverUrl: null,
  //             trackLikeCount: 0,
  //             comments: [],
  //           ),
  //           trackOrder: 2,
  //         ),
  //       ],
  //     ),
  //     Playlist(
  //       id: 8,
  //       title: 'Party Hits',
  //       isPublic: true,
  //       shareCount: 110, // 예시 값
  //       tracks: [
  //         PlaylistTrackItem(
  //           track: Track(
  //             trackId: 16,
  //             trackTitle: 'song1',
  //             artistName: 'Artist1',
  //             composer: [''],
  //             lyricist: [''],
  //             albumId: 8,
  //             trackFileUrl: '',
  //             lyric: '',
  //             trackNumber: 1,
  //             commentCount: 0,
  //             createdAt: DateTime.now().toString(),
  //             coverUrl: null,
  //             trackLikeCount: 0,
  //             comments: [],
  //           ),
  //           trackOrder: 1,
  //         ),
  //         PlaylistTrackItem(
  //           track: Track(
  //             trackId: 17,
  //             trackTitle: 'song2',
  //             artistName: 'Artist2',
  //             composer: [''],
  //             lyricist: [''],
  //             albumId: 8,
  //             trackFileUrl: '',
  //             lyric: '',
  //             trackNumber: 2,
  //             commentCount: 0,
  //             createdAt: DateTime.now().toString(),
  //             coverUrl: null,
  //             trackLikeCount: 0,
  //             comments: [],
  //           ),
  //           trackOrder: 2,
  //         ),
  //       ],
  //     ),
  //     Playlist(
  //       id: 9,
  //       title: 'Acoustic Sessions',
  //       isPublic: true,
  //       shareCount: 65, // 예시 값
  //       tracks: [
  //         PlaylistTrackItem(
  //           track: Track(
  //             trackId: 18,
  //             trackTitle: 'song1',
  //             artistName: 'Artist1',
  //             composer: [''],
  //             lyricist: [''],
  //             albumId: 9,
  //             trackFileUrl: '',
  //             lyric: '',
  //             trackNumber: 1,
  //             commentCount: 0,
  //             createdAt: DateTime.now().toString(),
  //             coverUrl: null,
  //             trackLikeCount: 0,
  //             comments: [],
  //           ),
  //           trackOrder: 1,
  //         ),
  //         PlaylistTrackItem(
  //           track: Track(
  //             trackId: 19,
  //             trackTitle: 'song2',
  //             artistName: 'Artist2',
  //             composer: [''],
  //             lyricist: [''],
  //             albumId: 9,
  //             trackFileUrl: '',
  //             lyric: '',
  //             trackNumber: 2,
  //             commentCount: 0,
  //             createdAt: DateTime.now().toString(),
  //             coverUrl: null,
  //             trackLikeCount: 0,
  //             comments: [],
  //           ),
  //           trackOrder: 2,
  //         ),
  //       ],
  //     ),
  //     Playlist(
  //       id: 10,
  //       title: 'Electronic Essentials',
  //       isPublic: true,
  //       shareCount: 95, // 예시 값
  //       tracks: [
  //         PlaylistTrackItem(
  //           track: Track(
  //             trackId: 20,
  //             trackTitle: 'song1',
  //             artistName: 'Artist1',
  //             composer: [''],
  //             lyricist: [''],
  //             albumId: 10,
  //             trackFileUrl: '',
  //             lyric: '',
  //             trackNumber: 1,
  //             commentCount: 0,
  //             createdAt: DateTime.now().toString(),
  //             coverUrl: null,
  //             trackLikeCount: 0,
  //             comments: [],
  //           ),
  //           trackOrder: 1,
  //         ),
  //         PlaylistTrackItem(
  //           track: Track(
  //             trackId: 21,
  //             trackTitle: 'song2',
  //             artistName: 'Artist2',
  //             composer: [''],
  //             lyricist: [''],
  //             albumId: 10,
  //             trackFileUrl: '',
  //             lyric: '',
  //             trackNumber: 2,
  //             commentCount: 0,
  //             createdAt: DateTime.now().toString(),
  //             coverUrl: null,
  //             trackLikeCount: 0,
  //             comments: [],
  //           ),
  //           trackOrder: 2,
  //         ),
  //       ],
  //     ),
  //   ];
  // }

  static List<Track> getHot50Titles() {
    return List.generate(50, (index) {
      int id = index + 1;
      return Track(
        id: id,
        composer: 'Composer $id',
        lyricist: 'Lyricist $id',
        lyrics: 'Lyrics for track $id',
        trackTitle: 'Track Title $id',
        artist: 'Artist $id',
        albumId: 'album$id',
        trackFileUrl: 'https://example.com/song$id.mp3',
      );
    });
  }
}
